### ISSUE TITLE
Database locks at pyGI.db

### ISSUE THREAD

**Issue by kourt999** [s55ma/granzscientific-geiger-counter-APRS#1]
Greetings,

The pyGIwriteFile.py script errors out with the following output:

pi@raspberrypi:~/pi-zero-geiger-counter/pi-software $ ./pyGIwriteFile.py &
[3] 1637
pi@raspberrypi:~/pi-zero-geiger-counter/pi-software $ 2020-05-17 18:21:30,053 INFO root: Starting pyGIconsole
2020-05-17 18:21:30,132 INFO pyGI.geigerlog: Getting last totalcount
Traceback (most recent call last):
  File "./pyGIwriteFile.py", line 25, in <module>
    (last_total,last_total_dtc) = geigerlog.get_last_totalcount()
  File "/home/pi/pi-zero-geiger-counter/pi-software/pyGI/geigerlog.py", line 25, in get_last_totalcount
    db = leveldb.LevelDB(cfg.get('db','path'))
leveldb.LevelDBError: IO error: lock log/pyGI.db/LOCK: Resource temporarily unavailable

[3]+  Exit 1                  ./pyGIwriteFile.py
pi@raspberrypi:~/pi-zero-geiger-counter/pi-software $ 

Any idea what may be causing this?

**Comment by s55ma** [comment]
This usually means another pyGI process is already using the LevelDB database at `log/pyGI.db`.

Check for running copies:

ps aux | grep pyGI
